name: diary_app
description: "Diary app with calendar & logging"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  table_calendar: ^3.0.9
  intl: ^0.19.0
  device_info_plus: ^10.1.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: true
    ios: false
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/avatar/
    - assets/themes/miku/
    - assets/themes/rin/
    - assets/themes/ichika/
    - assets/themes/mafuyu/
    - assets/themes/saki/
    - assets/themes/kanade/
    - assets/themes/nene/
    - assets/themes/kohane/
    - assets/themes/haruka/
    - assets/themes/emu/
    - assets/themes/ena/
    - assets/themes/airi/
